name: jewellery
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  get: ^4.6.6
  shimmer: ^3.0.0
  http: ^1.2.2
  provider: ^6.1.2
  go_router: ^14.6.3
  flutter_animate: ^4.5.2
  visibility_detector: ^0.4.0+2
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.11
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.5
  intl: ^0.19.0

  universal_html: ^2.2.4

flutter:

  uses-material-design: true
